//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WildernessSurvival.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class AppResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("WildernessSurvival.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENERGY.
        /// </summary>
        internal static string AttrEnergy {
            get {
                return ResourceManager.GetString("AttrEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD.
        /// </summary>
        internal static string AttrFood {
            get {
                return ResourceManager.GetString("AttrFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEALTH.
        /// </summary>
        internal static string AttrHealth {
            get {
                return ResourceManager.GetString("AttrHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string AttrLocation {
            get {
                return ResourceManager.GetString("AttrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATER.
        /// </summary>
        internal static string AttrWater {
            get {
                return ResourceManager.GetString("AttrWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack.
        /// </summary>
        internal static string Backpack {
            get {
                return ResourceManager.GetString("Backpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campfire.
        /// </summary>
        internal static string Campfire {
            get {
                return ResourceManager.GetString("Campfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        internal static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one to cook.
        /// </summary>
        internal static string CookTip {
            get {
                return ResourceManager.GetString("CookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Down.
        /// </summary>
        internal static string CutDownTree {
            get {
                return ResourceManager.GetString("CutDownTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt.
        /// </summary>
        internal static string Hunt {
            get {
                return ResourceManager.GetString("Hunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one to use.
        /// </summary>
        internal static string UseTip {
            get {
                return ResourceManager.GetString("UseTip", resourceCulture);
            }
        }
    }
}
