using System.Collections.Generic;
using System.Globalization;

namespace WildernessSurvival.Localization
{
    public class LangEn : ILocalization
    {
        public CultureInfo BoundCulture { get; } = new CultureInfo("en");

        public Dictionary<string, string> TranslationKey2Localized { get; } = new Dictionary<string, string>
        {
            { "Attr.Health", "HEALTH" },
            { "Attr.Food", "FOOD" },
            { "Attr.Water", "WATER" },
            { "Attr.Energy", "ENERGY" },
            { "Attr.Location", "LOCATION" },
            { "Item.Log.Name", "Log" },
            { "Item.Log.Desc", "An unremarkable piece of wood." },
            { "Item.EnergyBar.Name", "Energy Bar" },
            { "Item.EnergyBar.Desc", "You're not you when you're hungry." },
            { "Item.OldOxe.Name", "Old Oxe" },
            { "Item.OldOxe.Desc", "An old axe, but still sharp." },
            { "Item.BottledWater.Name", "Bottled Water" },
            { "Item.BottledWater.Desc", "A bottle of water, no one knows how long it has been stored." },
            { "Item.PlasticBottle.Name", "Plastic Bottle" },
            { "Item.PlasticBottle.Desc", "The best material, gift from industry." },
            { "Item.RawRabbit.Name", "Raw Rabbit" },
            { "Item.RawRabbit.Desc", "No fat, rich in protein." },
            { "Item.CookedRabbit.Name", "Cooked Rabbit" },
            { "Item.CookedRabbit.Desc", "Good smell." },
            { "Item.OldFishRod.Name", "Old Fish Rod" },
            { "Item.OldFishRod.Desc", "Now go fishing." },
            { "Item.Berry.Name", "Berry" },
            { "Item.Berry.Desc", "It reminds me of jam." },
            { "Item.RoastedBerry.Name", "Roasted Berry" },
            { "Item.RoastedBerry.Desc", "Slimy." },
            { "Item.DirtyWater.Name", "Dirty Water" },
            { "Item.DirtyWater.Desc", "It's better to boil." },
            { "Item.CleanWater.Name", "Clean Water" },
            { "Item.CleanWater.Desc", "Quenching your thirst." },
            { "Item.Nuts.Name", "Nuts" },
            { "Item.Nuts.Desc", "Where is my nutcracker?" },
            { "Item.ToastedNuts.Name", "Toasted Nuts" },
            { "Item.ToastedNuts.Desc", "Now I don't need any nutcracker." },
            { "Item.Bandage.Name", "Bandage" },
            { "Item.Bandage.Desc", "No more wounds." },
            { "Item.FistAidKit.Name", "Fist Aid Kit" },
            { "Item.FistAidKit.Desc", "I need healing!" },
            { "Item.EnergyDrink.Name", "Energy Drink" },
            { "Item.EnergyDrink.Desc", "Watch out the beast." },
            { "Item.RawFish.Name", "Raw Fish" },
            { "Item.RawFish.Desc", "Phishing." },
            { "Item.CookedFish.Name", "Cooked Fish" },
            { "Item.CookedFish.Desc", "Good smell." },
            { "Item.OldShotgun.Name", "Old Shotgun" },
            { "Item.OldShotgun.Desc", "It still can work." },
            { "Item.Trap.Name", "Trap" },
            { "Item.Trap.Desc", "Wait and see." },
            { "Item.Sticks.Name", "Sticks" },
            { "Item.Sticks.Desc", "Common sticks that you can find anywhere." },
            { "Item.CutGrass.Name", "Cut Grass" },
            { "Item.CutGrass.Desc", "It's not green and but still renewable." },
            { "Item.HandDrillKit.Name", "Hand Drill Kit" },
            { "Item.HandDrillKit.Desc", "To start a fire, but it's not as easy as TV show." },
            { "Item.UnknownMushrooms.Name", "Unknown Mushrooms" },
            { "Item.UnknownMushrooms.Desc", "Don't touch bright mushrooms. Well, let you have a taste." },
            { "Item.GrilledUnknownMushrooms.Name", "Grilled Unknown Mushrooms" },
            { "Item.GrilledUnknownMushrooms.Desc", "Hope the fire will cleanse the poison." },
            { "Cook.Cook", "Cook" },
            { "Cook.Boil", "Boil" },
            { "Cook.Roast", "Roast" },
            { "Cook.Tip", "Select one to cook" },
            { "Cook.Header", "Campfire" },
            { "Cook.LowFuel", "Low Fuel" },
            { "Cook.AfterCook", "After Cooked: {0}" },
            { "Cook.AfterBoil", "After Boiled: {0}" },
            { "Cook.AfterRoast", "After Roasted: {0}" },
            { "Craft.Header", "Crafting" },
            { "Craft.Tip", "Select one to craft" },
            { "Craft.Craft", "Craft" },
            { "Craft.AfterCraft", "After Craft" },
            { "Fire.Header", "Campfire" },
            { "Fire.Throw", "Throw" },
            { "Fire.Tip", "Select to fill the fuel." },
            { "Fire.Fuel", "Fuel" },
            { "Fire.Success", "Cool! You started a fire!" },
            { "Fire.Failed.Wet", "It's too wet, you'd better find another place." },
            { "Fire.Failed.FireRate", "It does not work well. You failed to make a fire." },
            { "Fire.PutOut.Move", "It's time to move, you put out the campfire." },
            { "Backpack.Header", "Backpack" },
            { "Backpack.CannotUse", "Can't Use" },
            { "Backpack.Use", "Use" },
            { "Backpack.Tip", "Select one to use" },
            { "Backpack.Eat", "Eat" },
            { "Backpack.Drink", "Drink" },
            { "Backpack.AfterUse", "After Use" },
            { "Backpack.AfterEat", "After Eat" },
            { "Backpack.AfterDrink", "After Drink" },
            { "Dialog.Failed.Title", "Failed" },
            { "Dialog.Failed.Content", "You died, but you still tried {0} times." },
            { "Dialog.Failed.Accept", "Restart" },
            { "Dialog.Failed.Cancel", "Not Now" },
            { "Dialog.Win.Title", "Congratulation!" },
            { "Dialog.Win.Content", "You escape from the wild after {0} actions!" },
            { "Dialog.Win.Accept", "Play Again" },
            { "Dialog.Win.Cancel", "Not Now" },
            { "Dialog.DisplayGainedItems.Title", "Result" },
            { "Dialog.DisplayGainedItems.Content", "You got {0}." },
            { "Dialog.DisplayNoItemGained.Title", "Too Bad" },
            { "Dialog.DisplayNoItemGained.Content", "You got nothing." },
            { "Route.Subtropics", "Subtropics" },
            { "Route.Subtropics.Plain", "Plain" },
            { "Route.Subtropics.Riverside", "Riverside" },
            { "Route.Subtropics.Forest", "Forest" },
            { "Route.Subtropics.Hut", "Hut" },
            { "Route.Subtropics.Cave", "Cave" },
            { "Action.Move", "Move" },
            { "Action.Explore", "Explore" },
            { "Action.Rest", "Rest" },
            { "Action.Fire", "Fire" },
            { "Action.Hunt", "Hunt" },
            { "Action.CutDownTree", "Cut Down" },
            { "Action.Fish", "Fish" },
            { "Action.Restart", "Restart" },
            { "Action.Backpack", "Backpack" },
            { "Action.Cook", "Cook" },
            { "Action.Craft", "Craft" },
            { "Subtropics.Common.Rest", "You took a break and feel better." },
            { "Subtropics.Hut.Rest", "In a warm hut, you slept soundly." },
            { "Tool.Broken", "{0} is completely broken, cannot be used any more." },
            { "OK", "OK" },
            { "Oops", "Oops!" },
            { "Alright", "Alright" }
        };
    }
}