using System.Collections.Generic;
using System.Globalization;

namespace WildernessSurvival.Localization
{
    public class LangZhCn : ILocalization
    {
        public CultureInfo BoundCulture { get; } = new CultureInfo("zh-CN");

        public Dictionary<string, string> TranslationKey2Localized { get; } = new Dictionary<string, string>
        {
            { "Attr.Health", "生命" },
            { "Attr.Food", "饱腹" },
            { "Attr.Water", "饮水" },
            { "Attr.Energy", "体力" },
            { "Attr.Location", "地点" },
            { "Item.Log.Name", "木头" },
            { "Item.Log.Desc", "一根没什么特点的木头。" },
            { "Item.EnergyBar.Name", "能量棒" },
            { "Item.EnergyBar.Desc", "嗯，来劲了。" },
            { "Item.OldOxe.Name", "老旧的斧头" },
            { "Item.OldOxe.Desc", "一把老旧的斧头，但是木柄还是很结实。" },
            { "Item.BottledWater.Name", "瓶装水" },
            { "Item.BottledWater.Desc", "一瓶矿泉水，不知道放了多久。" },
            { "Item.RawRabbit.Name", "生兔肉" },
            { "Item.RawRabbit.Desc", "新鲜的生兔肉，你觉得应该烧熟了再吃。" },
            { "Item.CookedRabbit.Name", "烤兔肉" },
            { "Item.CookedRabbit.Desc", "兔兔辣么可爱，你为什么要吃兔兔。" },
            { "Item.OldFishRod.Name", "老旧的钓鱼竿" },
            { "Item.OldFishRod.Desc", "一根老旧的钓鱼竿，应该还可以钓鱼。" },
            { "Item.Berry.Name", "浆果" },
            { "Item.Berry.Desc", "在别的游戏里，我可是主角。" },
            { "Item.DirtyWater.Name", "脏水" },
            { "Item.DirtyWater.Desc", "你觉得应该烧开了再喝。" },
            { "Item.CleanWater.Name", "净水" },
            { "Item.CleanWater.Desc", "干净的水，正好解渴。" },
            { "Item.Nuts.Name", "坚果" },
            { "Item.Nuts.Desc", "芜香蛋。" },
            { "Item.Bandage.Name", "绷带" },
            { "Item.Bandage.Desc", "用来包扎伤口。" },
            { "Item.FistAidKit.Name", "急救包" },
            { "Item.FistAidKit.Desc", "等我打个包先。" },
            { "Item.EnergyDrink.Name", "能量饮料" },
            { "Item.EnergyDrink.Desc", "让你随时麦动回来。" },
            { "Item.RawFish.Name", "生鱼" },
            { "Item.RawFish.Desc", "红鲤鱼与绿鲤鱼与驴。" },
            { "Item.CookedFish.Name", "熟鱼" },
            { "Item.CookedFish.Desc", "授人以鱼不如授人以渔。" },
            { "Item.OldShotgun.Name", "老旧的猎枪" },
            { "Item.OldShotgun.Desc", "还是双管的。" },
            { "Item.Trap.Name", "捕兽陷阱" },
            { "Item.Trap.Desc", "应该没有傻子会自己踩到它吧。" },
            { "Cook.Cook", "烹饪" },
            { "Cook.CookTip", "选择要加热的东西" },
            { "Cook.Header", "篝火" },
            { "Cook.NoWood", "没有木头" },
            { "Cook.AfterCook", "烹饪后: {0}" },
            { "Cook.AfterBoil", "煮开后: {0}" },
            { "Backpack.Header", "背包" },
            { "Backpack.CannotUse", "不可使用" },
            { "Backpack.Use", "使用" },
            { "Backpack.UseTip", "选择要使用的物品" },
            { "Backpack.Eat", "食用" },
            { "Backpack.Drink", "饮用" },
            { "Backpack.AfterUse", "使用后" },
            { "Backpack.AfterEat", "食用后" },
            { "Backpack.AfterDrink", "饮用后" },
            { "Dialog.Failed.Title", "失败" },
            { "Dialog.Failed.Content", "你死了，撑过了 {0} 个回合。" },
            { "Dialog.Failed.Accept", "重新开始" },
            { "Dialog.Failed.Cancel", "再等等" },
            { "Dialog.Win.Title", "恭喜！" },
            { "Dialog.Win.Content", "经过了 {0} 个回合，你成功逃离了荒野！" },
            { "Dialog.Win.Accept", "再来一次" },
            { "Dialog.Win.Cancel", "再等等" },
            { "Dialog.DisplayGainedItems.Title", "结果" },
            { "Dialog.DisplayGainedItems.Content", "你获得了 {0}。" },
            { "Dialog.DisplayNoItemGained.Title", "太糟了" },
            { "Dialog.DisplayNoItemGained.Content", "你没有任何收获。" },
            { "Route.Subtropics", "亚热带" },
            { "Route.Subtropics.Plain", "平原" },
            { "Route.Subtropics.Riverside", "河边" },
            { "Route.Subtropics.Forest", "森林" },
            { "Route.Subtropics.Hut", "小屋" },
            { "Action.Move", "前进" },
            { "Action.Explore", "探索" },
            { "Action.Rest", "休息" },
            { "Action.Fire", "生火" },
            { "Action.Hunt", "打猎" },
            { "Action.CutDownTree", "砍树" },
            { "Action.Fish", "钓鱼" },
            { "Action.Restart", "重新开始" },
            { "Action.Backpack", "背包" },
            { "Action.Cook", "烹饪" },
            { "Subtropics.Common.Rest", "你休息了一会，感觉又充满了力量。" },
            { "Subtropics.Common.Fire", "你生起了火。" },
            { "OK", "好" },
            { "Alright", "Alright" }
        };
    }
}